inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true
  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/*"
    - "config/puma.rb"



# ルールの設定


# Naming
Naming/MemoizedInstanceVariableName:
  Exclude:
    - app/services/user_authenticate_service.rb
    - app/services/user_sessionize_service.rb


# Metrics
Metrics/AbcSize:
  Exclude:
    - "app/services/user_auth/access_token.rb"

Metrics/MethodLength:
  Exclude:
    - "app/services/user_auth/access_token.rb"



# Layout





# Style


# Lint
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - "app/services/user_auth/access_token.rb"





# ASCII以外の文字を含むコメント（日本語コメントなど）を許可
Style/AsciiComments:
  Enabled: false

# クラスやモジュールのネストされた宣言を許可
Style/ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さなくても良い
Style/Documentation:
  Enabled: false

# 文字列のfreeze（Ruby3からは自動でfreezeされるので要らない）
Style/FrozenStringLiteralComment:
  Enabled: false

# 文字列リテラルのダブルクォートチェックを無効化
Style/StringLiterals:
  Enabled: false

# シンボル配列の%記法に関するチェックを無効化
Style/SymbolArray:
  Enabled: false



# Rspec/FactoryBot

# 1つのテストケース（example）に対して複数の期待値を許可する
RSpec/MultipleExpectations:
  Exclude:
    - "spec/models/user_spec.rb"
    - "spec/requests/api/v1/refresh_token_spec.rb"

# テストグループのネスト深度を4までとする
RSpec/NestedGroups:
  Max: 4

# described_classは使用しない
RSpec/DescribedClass:
  Enabled: false

# 特定のテストではインスタンス変数を許可する
RSpec/InstanceVariable: 
  Exclude:
    - "spec/requests/api/v1/refresh_token_spec.rb"


# FactoryBot::Syntax::Methodsモジュールのbuildメソッドを使用しない
FactoryBot/SyntaxMethods:
  Enabled: false