name: Deploy

on: [push]

# TODO:起動条件の変更

# on:
#   pull_request:
#     branches:
#       - main
#     types: [closed]

env:
  AWS_REGION: ap-northeast-1
  PROMPTHUB_FRONT_SERVICE: prompthub-front-service
  PROMPTHUB_API_SERVICE: prompthub-api-service
  FRONT_CONTAINER_NAME: prompthub-front-container
  API_CONTAINER_NAME: prompthub-api-container
  FRONT_IMAGE_NAME: prompthub-front
  API_IMAGE_NAME: prompthub-api
  API_TAG: 0.0.1
  FRONT_TAG: 0.0.1

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: build image
      id: build-image
      run: |
        docker-compose build

    - name: front push to ECR
      id: build-image-front
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        cd api
        docker tag $FRONT_IMAGE_NAME $ECR_REGISTRY/$FRONT_IMAGE_NAME:latest
        docker push $ECR_REGISTRY/$FRONT_IMAGE_NAME:$WEBAPP_TAG
        docker push $ECR_REGISTRY/$FRONT_IMAGE_NAME:latest

    - name: api push to ECR
      id: build-image-api
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        cd api
        docker tag $API_IMAGE_NAME $ECR_REGISTRY/$API_IMAGE_NAME:latest
        docker push $ECR_REGISTRY/$API_IMAGE_NAME:$WEBAPP_TAG
        docker push $ECR_REGISTRY/$API_IMAGE_NAME:latest